### ISSUE TITLE
Wiki documentation broken link

### ISSUE THREAD

**Issue by brycegbrazen** [shotgunsoftware/tk-multi-importcut#71]
https://github.com/shotgunsoftware/tk-multi-importcut/wiki/Documentation has broken link to:

`https://support.shotgunsoftware.com/hc/en-us/articles/222911368-SG-7-0-Import-your-Cut`

That no longer exists. Can we link to the new doc page?

**Comment by julien-lang** [comment]
Thanks for the heads up @brycegbrazen. I think the new link would be https://help.autodesk.com/view/SGSUB/ENU/?guid=SG_Editorial_ed_import_cut_html
